version: 3

tasks:
  default:
    deps: [build,test]
  build:
    cmds:
      - go build -o foo .
  test:
    cmds:
      - go test -count=1 ./...
  verbose:
    cmds:
      - go test -count=1 -v ./...
